import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { Header } from "@/components/headers";
import { auth } from "@/lib/auth";
import Script from "next/script";
import { headers } from "next/headers";
import { Footer } from "@/components/footers";

/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

export const metadata: Metadata = {
  title: "Ordi'Simple",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers()
  })

  return (
    <html lang="fr" data-theme="light">
      <head>
        <link rel="icon" href="/logo.svg" />
        <Script src="http://51.68.120.20:3000/script.js" data-website-id="82c61f8f-b0f0-4b81-8e96-7e8237623f42"/>
      </head>
      <body className="flex flex-col min-h-screen"> 
        <Header session={session} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
